apiVersion: apps/v1
kind: Deployment
metadata:
  name: login
  labels:
    app: login
spec:
  replicas: 1
  selector:
    matchLabels:
      app: login
  template:
    metadata:
      labels:
        app: login
    spec:
      containers:
        - name: login
          image: gcr.io/<PROJECT_ID>/login:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
